[package]
name = "lua_interpreter"
version = "0.1.0"
authors = ["SentientTurtle"]
edition = "2018"
publish = false

[dependencies]
regex = "1.3.9"
nom = "5.1.1"
rand = "0.7"

[profile.test]
opt-level = 3